import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Building2, Check, CheckCircle2, ClipboardCheck, FileCheck2, History, Menu, MonitorCog, Paperclip, ShieldCheck, Snowflake, Wrench, X } from "lucide-react";

export const CLINIC_APP_URL = "https://clinicas.dentistech.com.br/";
export const TECH_APP_URL = "https://tecnicos.dentistech.com.br/";
const nav = [["Início","top"],["Como funciona","como-funciona"],["Soluções","solucoes"],["Planos","planos"],["Rede técnica","rede"],["Sobre","sobre"]];
const stages = ["Chamado aberto","Técnico acionado","Visita confirmada","Atendimento concluído"];
const steps = [
  ["01","A clínica abre o chamado","Informa o equipamento, descreve o problema e envia fotos quando necessário."],
  ["02","A demanda é direcionada","A plataforma organiza o atendimento e conecta a clínica a um técnico compatível."],
  ["03","O serviço é acompanhado","Status, visita e informações técnicas ficam centralizados durante o processo."],
  ["04","O histórico fica registrado","A clínica mantém um registro técnico para acompanhar manutenções e futuras decisões."],
];
const plans = [
  ["Standard","Consultórios com 1 a 2 cadeiras.","Uma rotina preventiva para estruturas menores, com acompanhamento dos equipamentos essenciais da operação.",["Manutenção preventiva programada","Atendimento para necessidades técnicas","Histórico registrado na plataforma","Estrutura adequada a consultórios compactos"]],
  ["Plus","Clínicas com 3 a 4 cadeiras.","Acompanhamento recorrente para clínicas que precisam de mais previsibilidade e organização técnica.",["Avaliação técnica inicial","Visitas programadas","Relatórios de acompanhamento","Cobertura adequada a uma operação em crescimento"]],
  ["Gold","Clínicas com 5 a 8 cadeiras e equipamentos avançados.","Gestão técnica ampliada para operações com maior volume, diversidade de equipamentos e menor tolerância a interrupções.",["Avaliação técnica completa","Acompanhamento de estrutura ampliada","Equipamentos avançados","Histórico e documentação centralizados"]],
];

function Link({href,children,className="button primary"}:{href:string;children:React.ReactNode;className?:string}){return <a href={href} className={className} target="_blank" rel="noopener noreferrer">{children}</a>}
function Demo({active}:{active:number}){return <div className="ticket" aria-label="Chamado técnico em andamento"><div className="ticketTop"><div><small>CHAMADO DT-0248</small><h3>Instituto Odontológico</h3></div><span className="live"><i/>Em andamento</span></div><div className="equipment"><MonitorCog/><div><small>Equipamento</small><b>Bomba a vácuo</b><span>Manutenção corretiva</span></div></div><div className="facts"><span><ShieldCheck/> Profissional verificado</span><span><Paperclip/> Fotos anexadas</span></div><div className="timeline">{stages.map((s,i)=><div className={i<=active?"stage done":"stage"} key={s}><span>{i<active?<Check/>:i+1}</span><div><b>{s}</b><small>{i===active?"Etapa atual":i<active?"Registrado":"Aguardando"}</small></div></div>)}</div><div className="resultBar"><CheckCircle2/><div><small>Status final</small><b>{active===3?"Equipamento funcionando":"Atendimento documentado"}</b></div></div></div>}
function Heading({tag,title,children}:{tag:string;title:string;children?:React.ReactNode}){return <div className="heading"><span className="kicker">{tag}</span><h2>{title}</h2>{children}</div>}

export default function Home(){
  const [menu,setMenu]=useState(false),[scrolled,setScrolled]=useState(false),[demo,setDemo]=useState(0),[guide,setGuide]=useState(0),[chairs,setChairs]=useState("1-2"),[advanced,setAdvanced]=useState<string[]>([]),[climate,setClimate]=useState("Não");
  useEffect(()=>{const onScroll=()=>setScrolled(scrollY>24);onScroll();addEventListener("scroll",onScroll,{passive:true});const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const timer=reduced?0:setInterval(()=>setDemo(v=>(v+1)%4),3200);return()=>{removeEventListener("scroll",onScroll);if(timer)clearInterval(timer)}},[]);
  const recommendation=useMemo(()=>chairs==="8+"?"Avaliação personalizada":chairs==="5-8"||(advanced.length>=2&&chairs!=="1-2")?"Gold":chairs==="3-4"?"Plus":"Standard",[chairs,advanced]);
  const toggle=(v:string)=>setAdvanced(a=>a.includes(v)?a.filter(x=>x!==v):[...a,v]);
  return <main id="top">
    <header className={scrolled?"siteHeader scrolled":"siteHeader"}><div className="container headerInner"><a className="brand" href="#top"><img src="/LOGO_DENTISTECH.png" alt=""/><b>DentisTech</b></a><nav className={menu?"nav open":"nav"} aria-label="Navegação principal">{nav.map(([l,id])=><a href={`#${id}`} onClick={()=>setMenu(false)} key={id}>{l}</a>)}<Link href={CLINIC_APP_URL} className="button headerCta">Entrar no app <ArrowRight/></Link></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label={menu?"Fechar menu":"Abrir menu"}>{menu?<X/>:<Menu/>}</button></div></header>
    <section className="hero"><div className="gridBg"/><div className="container heroInner"><div><span className="eyebrow"><i/> EM OPERAÇÃO • UBERLÂNDIA — MG</span><h1>A infraestrutura técnica que mantém sua clínica funcionando.</h1><p>Abra chamados, acione técnicos verificados, acompanhe cada atendimento e mantenha o histórico dos seus equipamentos em um só lugar.</p><div className="actions"><Link href={CLINIC_APP_URL}>Abrir um chamado <ArrowRight/></Link><a className="button secondary" href="#como-funciona">Ver como funciona</a></div><small className="heroNote"><Building2/> Plataforma para clínicas odontológicas e profissionais técnicos.</small></div><div><Demo active={demo}/><small className="demoNote"><i/> Atualização do chamado em tempo real</small></div></div></section>
    <section className="section"><div className="container"><Heading tag="OPERAÇÃO CONTÍNUA" title="Quando um equipamento para, a operação inteira sente."><p>Agenda, equipe, pacientes e faturamento dependem de uma estrutura que funcione. A DentisTech encurta o caminho entre o problema e a solução e mantém cada atendimento técnico documentado.</p></Heading><div className="features">{[[ClipboardCheck,"Resposta organizada","Abra o chamado pela plataforma e concentre as informações do problema em um único lugar."],[Wrench,"Profissional compatível","A demanda é direcionada para um técnico de acordo com o equipamento e o tipo de atendimento."],[History,"Histórico preservado","Diagnósticos, registros e serviços realizados permanecem vinculados à clínica."]].map(([Icon,t,d]:any,i)=><article key={t}><Icon/><em>0{i+1}</em><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
    <section id="como-funciona" className="section alt"><div className="container"><Heading tag="COMO FUNCIONA" title="Do chamado ao equipamento funcionando."><p>Um fluxo técnico claro, com cada decisão e atendimento no lugar certo.</p></Heading><div className="how"><div>{steps.map(([n,t,d],i)=><button className={guide===i?"step active":"step"} onClick={()=>setGuide(i)} key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></button>)}</div><div className="sticky"><Demo active={guide}/></div></div></div></section>
    <section id="solucoes" className="section"><div className="container"><Heading tag="SOLUÇÕES" title="Uma estrutura técnica para cada momento da clínica."/><div className="three">{[["CHAMADOS TÉCNICOS","Resolva o problema que já apareceu.","Abra uma solicitação, informe o equipamento e acompanhe o atendimento pela plataforma.",["Abertura digital do chamado","Direcionamento da demanda","Registro do atendimento","Histórico técnico da clínica"]],["MANUTENÇÃO PREVENTIVA","Organize a manutenção antes da próxima falha.","Planos recorrentes para acompanhar equipamentos, programar visitas e dar mais previsibilidade à operação.",["Rotina preventiva","Visitas programadas","Relatórios técnicos","Acompanhamento recorrente","Escopo adequado ao porte da clínica"]],["GESTÃO TÉCNICA","Informação técnica que não se perde no WhatsApp.","Centralize equipamentos, ocorrências, registros, fotos e atendimentos em um ambiente organizado.",["Cadastro de equipamentos","Histórico de intervenções","Registro de diagnósticos","Documentação vinculada à clínica","Visibilidade sobre cada atendimento"]]].map(([tag,t,d,items]:any,i)=><article className="card" key={tag}><em>0{i+1}</em><span className="kicker">{tag}</span><h3>{t}</h3><p>{d}</p><ul>{items.map((x:string)=><li key={x}><Check/>{x}</li>)}</ul>{i===0&&<Link href={CLINIC_APP_URL} className="textLink">Abrir chamado <ArrowRight/></Link>}</article>)}</div></div></section>
    <section id="planos" className="section alt"><div className="container"><Heading tag="PLANOS PREVENTIVOS" title="Manutenção compatível com a estrutura da sua clínica."><p>Os planos são definidos conforme quantidade de cadeiras, equipamentos instalados e nível de acompanhamento necessário.</p></Heading><div className="three plans">{plans.map(([name,fit,d,items]:any,i)=><article className={i===1?"card plan featured":"card plan"} key={name}><div><b className="planName">{name}</b><small>{fit}</small><p>{d}</p></div><ul>{items.map((x:string)=><li key={x}><Check/>{x}</li>)}</ul></article>)}</div><div className="pmoc"><Snowflake/><div><span className="kicker">SOLUÇÃO COMPLEMENTAR</span><h3>PMOC e manutenção de climatização</h3><p>Acompanhamento da climatização da clínica, com manutenção programada e documentação definida conforme a estrutura instalada.</p><small>Disponibilidade, escopo e indicação dependem de avaliação técnica.</small></div><Link href={CLINIC_APP_URL} className="button secondary">Solicitar avaliação <ArrowRight/></Link></div>
    <div className="recommender"><div><span className="kicker">RECOMENDADOR</span><h3>Encontre um ponto de partida.</h3><p>Responda três perguntas para receber uma indicação inicial. Isto não é um orçamento automático.</p></div><div className="questions"><fieldset><legend><span>1</span> Quantas cadeiras sua clínica possui?</legend><div className="options">{[["1-2","1 a 2"],["3-4","3 a 4"],["5-8","5 a 8"],["8+","Mais de 8"]].map(([v,l])=><label className={chairs===v?"selected":""} key={v}><input type="radio" name="chairs" checked={chairs===v} onChange={()=>setChairs(v)}/>{l}</label>)}</div></fieldset><fieldset><legend><span>2</span> Sua clínica possui equipamentos avançados?</legend><div className="options">{["Raio-X","Ultrassom","Bomba de vácuo","Outros","Nenhum desses"].map(v=><label className={advanced.includes(v)?"selected":""} key={v}><input type="checkbox" checked={advanced.includes(v)} onChange={()=>toggle(v)}/>{v}</label>)}</div></fieldset><fieldset><legend><span>3</span> Precisa organizar também a climatização?</legend><div className="options">{["Sim","Não","Quero entender melhor"].map(v=><label className={climate===v?"selected":""} key={v}><input type="radio" name="climate" checked={climate===v} onChange={()=>setClimate(v)}/>{v}</label>)}</div></fieldset><div className="recommendation"><div><small>INDICAÇÃO INICIAL</small><h4>{recommendation}</h4><p>A cobertura definitiva depende da avaliação da estrutura da clínica.{climate!=="Não"&&" Considere também o PMOC como solução complementar."}</p></div><Link href="https://wa.me/5534996403504">
  Conversar sobre este plano <ArrowRight />
</Link></div></div></div></div></section>
    <section id="rede" className="section"><div className="container"><Heading tag="REDE TÉCNICA" title="Uma rede técnica construída para gerar confiança."><p>A DentisTech aproxima clínicas odontológicas de profissionais técnicos e organiza o atendimento do início ao fim.</p></Heading><div className="criteria">{[[ShieldCheck,"Cadastro e verificação profissional"],[MonitorCog,"Compatibilidade com o tipo de equipamento"],[ClipboardCheck,"Atendimento documentado"],[History,"Histórico dentro da plataforma"]].map(([Icon,t]:any)=><div key={t}><Icon/><span>{t}</span></div>)}</div><div className="techCta"><div><span className="kicker">PARA PROFISSIONAIS</span><h3>Você trabalha com manutenção odontológica?</h3><p>Faça parte da rede DentisTech, receba oportunidades compatíveis com sua atuação e organize seus atendimentos pela plataforma.</p></div><Link href={TECH_APP_URL} className="button secondary">Quero ser técnico parceiro <ArrowRight/></Link></div></div></section>
    <section id="sobre" className="section alt"><div className="container about"><Heading tag="SOBRE A DENTISTECH" title="Tecnologia aplicada à manutenção odontológica."><p>A DentisTech é uma startup de tecnologia e manutenção odontológica que conecta clínicas a profissionais técnicos e organiza toda a jornada do atendimento em uma única plataforma.</p><p>A operação começou em Uberlândia, Minas Gerais, com uma proposta direta: reduzir o tempo perdido com manutenção, melhorar a organização técnica das clínicas e construir uma relação mais segura entre quem precisa do atendimento e quem executa o serviço.</p></Heading><div className="connection"><div><Building2/>Clínica</div><i/><div className="core"><img src="/LOGO_DENTISTECH.png" alt=""/>DentisTech</div><i/><div><Wrench/>Técnico</div><i/><div><FileCheck2/>Histórico técnico</div></div></div></section>
    <section className="final"><div className="container"><span className="kicker">OPERAÇÃO ORGANIZADA</span><h2>Sua clínica precisa funcionar. A manutenção também.</h2><p>Abra um chamado pela DentisTech e organize o atendimento técnico da sua clínica em um só lugar.</p><div className="actions"><Link href={CLINIC_APP_URL}>Abrir um chamado <ArrowRight/></Link><Link href={TECH_APP_URL} className="button secondary">Sou técnico</Link></div></div></section>
    <footer><div className="container footer"><div><a className="brand" href="#top"><img src="/LOGO_DENTISTECH.png" alt=""/><b>DentisTech</b></a><p>Infraestrutura técnica para manter clínicas odontológicas funcionando.</p></div><div><b>PLATAFORMA</b><Link href={CLINIC_APP_URL} className="footerLink">Para clínicas</Link><Link href={TECH_APP_URL} className="footerLink">Para técnicos</Link></div><div><b>OPERAÇÃO</b><span>Uberlândia — MG</span><span>© {new Date().getFullYear()} DentisTech</span></div></div></footer>
  </main>
}
